/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NYuNbgxNTqZ
 */
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function TodoList() {
  return (
    <>
      <header className="flex h-16 w-full items-center px-4 md:px-6">
        <Link className="flex items-center gap-2 font-semibold" href="#">
          <ListIcon className="h-6 w-6" />
          <span>TodoList</span>
        </Link>
        <DropdownMenu className="ml-auto">
          <DropdownMenuTrigger asChild>
            <Button
              className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800 ml-auto"
              size="icon"
              variant="ghost"
            >
              <Avatar>
                <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                <AvatarFallback>U</AvatarFallback>
              </Avatar>
              <span className="sr-only">Toggle user menu</span>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>My Account</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Settings</DropdownMenuItem>
            <DropdownMenuItem>Support</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Logout</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </header>
      <main className="p-4 md:p-6">
        <Card className="mb-6 md:mb-8 group relative">
          <CardHeader>
            <CardTitle>Buy Groceries</CardTitle>
            <Badge>Personal</Badge>
          </CardHeader>
          <CardContent>
            <p>Created by: John Doe</p>
            <p>Status: Incomplete</p>
          </CardContent>
          <div className="absolute right-0 top-0 mt-4 mr-4 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
            <Button className="mr-2">
              <PencilIcon className="w-4 h-4" /> Edit
            </Button>
            <Button>
              <TrashIcon className="w-4 h-4" /> Delete
            </Button>
          </div>
        </Card>
        <Card className="mb-6 md:mb-8 group relative">
          <CardHeader>
            <CardTitle>Finish Project Report</CardTitle>
            <Badge>Work</Badge>
          </CardHeader>
          <CardContent>
            <p>Created by: Jane Smith</p>
            <p>Status: Complete</p>
          </CardContent>
          <div className="absolute right-0 top-0 mt-4 mr-4 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
            <Button className="mr-2">
              <PencilIcon className="w-4 h-4" /> Edit
            </Button>
            <Button>
              <TrashIcon className="w-4 h-4" /> Delete
            </Button>
          </div>
        </Card>
        <form className="mb-6 md:mb-8">
          <label className="block mb-2" htmlFor="task">
            Task
          </label>
          <input
            className="w-full p-2 mb-4 border border-gray-200 rounded"
            id="task"
            name="task"
            placeholder="Enter task"
            required
            type="text"
          />
          <label className="block mb-2" htmlFor="category">
            Category
          </label>
          <select className="w-full p-2 mb-4 border border-gray-200 rounded" id="category" name="category" required>
            <option value="">Select category</option>
            <option value="personal">Personal</option>
            <option value="work">Work</option>
          </select>
          <Button className="w-full md:w-auto" type="submit">
            Add new task
          </Button>
          <Button className="w-full md:w-auto mt-2" type="button">
            Update task
          </Button>
        </form>
      </main>
    </>
  )
}


function ListIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>
  )
}


function PencilIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>
  )
}


function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}
